#!/bin/sh

set -e

itf=wlan0

mkdir -p /tmp/lib/misc
touch /tmp/lib/misc/udhcpd.leases
mkdir -p /dev/pts

mount devpts /dev/pts -t devpts

/sbin/ip address add 127.0.0.1/8 scope host dev lo
/sbin/ip link set up lo

# (re-)configure ${itf} in case hotplug call was attempted before rootfs was ok
if [ -e "/sys/class/net/${itf}" ]; then
	SUBSYSTEM="net" ACTION="add" INTERFACE="${itf}" /bin/config_network
fi

# make the led on pin 13 blink
(
	/bin/tests_gpio high
	sleep 1
	/bin/tests_gpio low
	sleep 1
	/bin/tests_gpio high
	sleep 1
	/bin/tests_gpio low
	sleep 1
	/bin/tests_gpio high
	sleep 1
	/bin/tests_gpio low
) &
